config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'home#index'
  post '/mypage/new', to: 'mypage#new', as: 'new_mypage'
  post '/mypage/destroy', to: 'mypage#destroy', as: 'destroy_mypage'
  post '/mypage/create', to: 'mypage#create', as: 'create_mypage'
  post '/mypage/increase_points', to: 'mypage#increase_points', as: 'increase_points_mypage' # テスト用
  post 'search/create', to: 'search#create', as: 'create_search'
  get 'search/update', to: 'search#update', as: 'update_search'
  resources :search, only: [:index, :new, :show]
  resource :mypage, controller: 'mypage', only: [:show, :new, :destroy, :create]
end

app/controllers/search_controller.rb
require 'net/http'
require 'uri'
require 'json'
require 'geocoder'
require 'date'


class SearchController < ApplicationController
  API_ENDPOINT = "https://webservice.recruit.co.jp/hotpepper/gourmet/v1/"
  API_KEY = ENV['HOTPEPPER_API_KEY'] # Updated line

  #現在位置を取得・検索距離を指定するページ
  def new
  end


  #店舗詳細画面の表示
  def show
    shop_id = params[:id]

    # ログインしているユーザーのIDを取得
    user_id = current_user.id if user_signed_in?

    # ユーザーがブックマークした店舗のIDを取得
    bookmarked_shop_ids = user_signed_in? ? Bookmark.where(user_id: current_user.id).pluck(:shop_id) : []

    uri = URI(API_ENDPOINT)
    api_params = {
      key: API_KEY,
      id: shop_id,
      format: 'json',
    }
    uri.query = URI.encode_www_form(api_params)

    res = Net::HTTP.get_response(uri)
    if res.is_a?(Net::HTTPSuccess)
      result = JSON.parse(res.body)
      if result['results'].nil? || result['results']['error'].present?
        flash[:alert] = '店舗情報の取得に失敗しました。もう一度試してください。'
        redirect_to search_index_path
      else
        @shop = result['results']['shop'][0]
        if @shop.nil?
          flash[:alert] = '店舗情報が見つかりませんでした。'
          redirect_to search_index_path
        else
          # ブックマークの確認
          if bookmarked_shop_ids && bookmarked_shop_ids.include?(@shop['id'])
            @shop['book'] = 1
          else
            @shop['book'] = 0
          end

          # レビューから店舗IDを取得し、DBに存在するか確認
          review = Review.find_by(shop_id: @shop['id'])
          if review.nil?
            @shop['point'] = { 'good' => 0, 'bad' => 0 }
          else
            @shop['point'] = { 'good' => review.good, 'bad' => review.bad }
          end

        end
      end
    else
      flash[:alert] = '店舗情報の取得に失敗しました。もう一度試してください。'
      redirect_to search_index_path
    end
  end

  #検索結果を表示するページ
  def index

    @page = params[:page].present? ? params[:page].to_i : 1
    @num = 15  # 1ページあたりの表示件数(最大100まで)
    start = (@page - 1) * @num + 1

    # 初期化エリア
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    @distance = params[:distance]
    @average_price = params[:average_price]
    @genre = params[:genre]
    @point = params[:point]

    uri = URI(API_ENDPOINT)
    api_params = {
      key: API_KEY,
      lat: params[:latitude],
      lng: params[:longitude],
      range: params[:distance],
      format: 'json',
      count: @num,
      start: start,
    }

    average_price = params[:average_price]
    genre = params[:genre]
    point = params[:point]

    #ソート機能
    if average_price != '0'
      api_params[:budget] = average_price
    end
    if genre != '0'
      api_params[:genre] = genre
    end



    #リクエスト送信
    uri.query = URI.encode_www_form(api_params)

    res = Net::HTTP.get_response(uri)
    if res.is_a?(Net::HTTPSuccess)
      result = JSON.parse(res.body)
      if result['results'].nil?
        flash[:alert] = '検索結果がありません。もう一度試してください。'
        redirect_to new_search_path
      elsif result['results']['error'].present?
        flash[:alert] = '検索に失敗しました。もう一度試してください。'
        redirect_to new_search_path
      else
        @shops = result['results']['shop']
        @total_results = result['results']['results_available'].to_i
        #検索結果の距離を計算
        @shops.each do |shop|
          shop_lat = shop['lat'].to_f
          shop_lng = shop['lng'].to_f
          user_lat = params[:latitude].to_f
          user_lng = params[:longitude].to_f

          distance = Geocoder::Calculations.distance_between([user_lat, user_lng], [shop_lat, shop_lng])
          if distance < 1
            shop['distance'] = (distance * 1000).round(2).to_s + 'm'
          else
            shop['distance'] = distance.round(2).to_s + 'km'
          end

          # レビューから店舗IDを取得し、DBに存在するか確認
          review = Review.find_by(shop_id: shop['id'])
          if review.nil?
            shop['point'] = { 'good' => 0, 'bad' => 0 }
          else
            shop['point'] = { 'good' => review.good, 'bad' => review.bad }
          end

          # 営業時間の判断を行い、shopに'now'を追加　ーーー作りかけーーー
          if shop['open'] =~ /(\w+～\w+): (\d+:\d+)～翌(\d+:\d+)/
            open_days, open_time, close_time = $1, $2, $3
            open_day_start, open_day_end = open_days.split("～").map { |day| days_jp_to_dt[day] }

            if open_day_start <= now.wday && now.wday <= open_day_end
              open_hour, open_minute = open_time.split(":").map(&:to_i)
              close_hour, close_minute = close_time.split(":").map(&:to_i)
              if open_hour <= now.hour && now.hour < 24 || 0 <= now.hour && now.hour < close_hour
                shop['now'] = "〇"
              else
                shop['now'] = "X"
              end
            else
              shop['now'] = "X"
            end
          else
            shop['now'] = "?"
          end
        end

        # ポイントに基づいてソート
        if point != '0'
          puts "point: #{point}"
          @shops.each do |shop|
            puts "shopid: #{shop['id']}, good: #{shop['point']['good']}, bad: #{shop['point']['bad']}"
          end
          @shops.sort_by! do |shop|
            case point
            when '1'
              -shop['point']['good'] # ＋ポイントが高い順
            when '2'
              -shop['point']['bad'] # ーポイントが高い順
            end
          end
        end
        render :index
      end
    else
      flash[:alert] = '検索に失敗しました。もう一度試してください。'
      redirect_to new_search_path
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<%= stylesheet_link_tag 'search_index' %>
<div class="header">
  <header>
    <h1>Finding Yummy</h1>
    <div class="header_menue">
      <% if user_signed_in? %>
        <%= link_to 'マイページ', mypage_path, class: 'header_mypage', target: "_blank" %>
        <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: 'header_mypage' %>
      <% end %>
    </div>
  </header>
</div>
<div class="searchmenu">
  <%= form_with url: search_index_path, method: :get, class: "search_menu" do |form| %>
    <%= form.hidden_field :latitude, value: params[:latitude] %>
    <%= form.hidden_field :longitude, value: params[:longitude] %>
    <%= form.hidden_field :distance, value: params[:distance] %>
    <%= form.hidden_field :page, value: @page %>
    

      <div class="money">
        <%= form.label :average_price, "平均価格" %>
        <%= form.select :average_price, options_for_select([
          ['指定しない', '0'],
          ['～500円', 'B009'],
          ['501～1000円', 'B010'],
          ['1001～1500円', 'B011'],
          ['1501～2000円', 'B001'],
          ['2001～3000円', 'B002'],
          ['3001～4000円', 'B003'],
          ['4001～5000円', 'B008'],
          ['5001～7000円', 'B004'],
          ['7001～10000円', 'B005'],
          ['10001～15000円', 'B006'],
          ['15001～20000円', 'B012'],
          ['20001～30000円', 'B013'],
          ['30001円～', 'B014']
        ]) %>
      </div>
      <div class="genre">
        <%= form.label :genre, "ジャンル" %>
        <%= form.select :genre, options_for_select([
          ['指定しない', '0'],
          ['居酒屋', 'G001'],
          ['ダイニングバー・バル', 'G002'],
          ['創作料理', 'G003'],
          ['和食', 'G004'],
          ['洋食', 'G005'],
          ['イタリアン・フレンチ', 'G006'],
          ['中華', 'G007'],
          ['焼肉・ホルモン', 'G008'],
          ['韓国料理', 'G017'],
          ['アジア・エスニック料理', 'G009'],
          ['各国料理', 'G010'],
          ['カラオケ・パーティ', 'G011'],
          ['バー・カクテル', 'G012'],
          ['ラーメン', 'G013'],
          ['お好み焼き・もんじゃ', 'G016'],
          ['カフェ・スイーツ', 'G014'],
          ['その他グルメ', 'G015']
        ]) %>
      </div>
      <div class="point">
        <%= form.label :point, "ポイント" %>
        <%= form.select :point, options_for_select([
          ['指定しない', '0'],
          ['＋ポイントが高い順', '1'],
          ['ーポイントが高い順', '2'],
        ]) %>
      </div>
      <%= form.submit "ソート開始" %>
  <% end %>
</div>
<div class="resaltinfo">
  <% @shops.each do |shop| %>
    <div class="shopinfo">
      <div class="detailadd">
        <div class="detailpoint">
          <div class="detail">
            <div class="photo">
              <!-- 写真 -->
              <% if shop['photo']['pc']['l'].present? %>
                <img src="<%= shop['photo']['pc']['l'] %>" alt="<%= shop['name'] %>の大きな写真（PC向け）">
              <% end %>
            </div>
            <table border="1">
              <tr>
                <!-- 名前、キャッチ-->
                <td colspan="3">
                  <strong><%= link_to "#{shop['name']}/#{shop['catch']}", search_path(id: shop['id']) %></strong>
                </td>
              </tr>
              <tr align="center">
                <td colspan="3">
                  <!-- アクセス、ジャンル、サブジャンル -->
                  <%= shop['address'] %> <br>
                  <% if shop['genre'] && shop['sub_genre'] %>
                    <%= shop['access'] %>/<%= shop['genre']['name'] %><%= shop['sub_genre']['name'] %>
                  <% elsif shop['genre'] %>
                    <%= shop['access'] %>/<%= shop['genre']['name'] %>
                  <% else %>
                    <%= shop['access'] %>
                  <% end %>
                </td>
              </tr>
              <tr>
                <!-- km now 円 -->
                <td><%= shop['distance'] %></td>
                <td>　<%= shop['now'] %>　</td>
                <td><%= shop['budget']['average'] || '情報なし' %></td>
              </tr>
            </table>
          </div>
          <div class="point">
            <table border="1">
              <tr>
                <td class="plas">
                  <strong><p>  <%= shop['point']['good'] %>P  </p></strong>
                </td>
                <td class="minus">
                  <strong><p>  <%= shop['point']['bad'] %>P  </p></strong>
              </tr>
            </table>
          </div>
        </div>
        <div class="add">
            <%= link_to "地図を開く", "https://www.google.com/maps/search/?api=1&query=#{URI.encode_www_form_component(shop['address'])}", target: "_blank" %>
            <%= link_to "店舗URL", shop['urls']['pc'], target: "_blank" %> 
        </div>

      </div>
    </div>
  <% end %>
</div>


<div class="footer_area">
  <div class="next_link">
    <%= link_to '前のページ', search_index_path(page: @page - 1, latitude: params[:latitude], longitude: params[:longitude], distance: params[:distance]) if @page > 1 %>
    <% if (@page * @num) < @total_results %>
      <%= link_to '次のページ', search_index_path(page: @page + 1, latitude: params[:latitude], longitude: params[:longitude], distance: params[:distance]) %>
    <% end %>
  </div>
  <footer>
    <p>Powered by <a href="http://webservice.recruit.co.jp/">ホットペッパーグルメ Webサービス</a></p>
  </footer>
</div>

app/views/search/new.html.erb
<script>
document.addEventListener('turbo:load', function() {
  disableRadiusButtons();
})

window.onload = function() {
  disableRadiusButtons();
}

function getLocation() {
  navigator.geolocation.getCurrentPosition(function(position) {
    document.getElementById('latitude').value = position.coords.latitude;
    document.getElementById('longitude').value = position.coords.longitude;
    enableRadiusButtons();
  });
}

function setRadius(value) {
  document.getElementById('distance').value = value;
  document.getElementById('search_form').submit();
}

function disableRadiusButtons() {
  var buttons = document.getElementsByClassName('radius-button');
  for (var i = 0; i < buttons.length; i++) {
    buttons[i].disabled = true;
  }
}

function enableRadiusButtons() {
  var buttons = document.getElementsByClassName('radius-button');
  for (var i = 0; i < buttons.length; i++) {
    buttons[i].disabled = false;
  }
}
</script>
<div class="header">
  <header>
    <h1>Finding Yummy</h1>
    <div class="header_menue">
      <% if user_signed_in? %>
        <%= link_to 'マイページ', mypage_path, class: 'header_mypage', target: "_blank" %>
        <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: 'header_mypage' %>
      <% end %>
    </div>
  </header>
</div>
<%= form_with url: search_index_path, method: :get, local: true, html: { id: 'search_form' } do |form| %>
  <%= button_tag '現在位置を取得', type: 'button', onclick: 'getLocation()' %>
  <%= hidden_field_tag :latitude, id: 'latitude' %>
  <%= hidden_field_tag :longitude, id: 'longitude' %>
  <%= hidden_field_tag :distance, id: 'distance' %>

  <%= button_tag '300m', type: 'button', onclick: 'setRadius(1)', class: 'radius-button' %>
  <%= button_tag '500m', type: 'button', onclick: 'setRadius(2)', class: 'radius-button' %>
  <%= button_tag '1km', type: 'button', onclick: 'setRadius(3)', class: 'radius-button' %>
  <%= button_tag '2km', type: 'button', onclick: 'setRadius(4)', class: 'radius-button' %>
  <%= button_tag '3km', type: 'button', onclick: 'setRadius(5)', class: 'radius-button' %>
<% end %>

<div class="footer_area">
  <footer>
      <p>Powered by <a href="http://webservice.recruit.co.jp/">ホットペッパーグルメ Webサービス</a></p>
  </footer>
</div>

app/views/search/show.html.erb
<div class="header">
  <header>
    <h1>Finding Yummy</h1>
    <div class="header_menue">
      <% if user_signed_in? %>
        <%= link_to 'マイページ', mypage_path, class: 'header_mypage', target: "_blank" %>
        <!-- 本当はリンクが良かったのですが、どう頑張ってもGETでしか送れず諦めました -->
        <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: 'header_mypage' %>
      <% end %>
    </div>
  </header>
</div>


<div class="show_shopinfo">
  <img class="shop-image" src="<%= @shop['photo']['pc']['l'] %>" alt="<%= @shop['name'] %>の画像">

  <h1><%= @shop['name'] %></h1>
  <%= form_with url: new_mypage_path, method: :post do |form| %>
    <div class="add">
      <% if user_signed_in? && @shop['book'] == 0 %>
        <%= form.hidden_field :shop_id, value: @shop['id'] %>
        <%= form.hidden_field :shop_name, value: "#{@shop['name']}/#{@shop['catch']}" %>
        <%= form.hidden_field :scroll_position, id: "scroll_position" %>
        <%= form.submit "ブックマーク" %>
      <% end %>
    </div>
  <% end %>

  
  <div class="name_area">
    <% if @shop['genre'] %>
      <p><%= @shop['genre']['name'] %></p>
      <% if @shop['genre']['sub'] %>
        <p><%= @shop['genre']['sub'] %></p>
      <% end %>
    <% end %>
  </div>

  <div class="address_area">
    <p><%= @shop['address'] %></p>
    <p><%= @shop['station_name'] %></p>
    <p><%= @shop['access'] %></p>
  </div>

  <div class="distance_area"><p><%= @shop['distance'] %></p></div>

  <div class="point_area">
      <p>ポイント:Good:<%= @shop['point']['good'] %> , Bad:<%= @shop['point']['bad'] %></p>
      <% if user_signed_in? %>
      <%= form_with url: create_mypage_path, method: :post do |form| %>
        <%= form.hidden_field :shop_id, value: @shop['id'] %>
        <%= form.label :good %>
        <%= form.number_field :good, in: 1000..10000, step: 1000 %>
        <%= form.label :bad %>
        <%= form.number_field :bad, in: 1000..10000, step: 1000 %>
        <%= form.submit 'ポイントを付ける' %>
      <% end %>
      <% end %>
  </div>

  <div class="open_area">
    <p>ランチ：<%= @shop['lunch'] %></p>
    <p><%= @shop['open'] %></p>
    <p><%= @shop['close'] %></p>
    <p>23時以降も: <%= @shop['midnight'] %></p>
  </div>

  <div class="money_area">
    <p><%= @shop['budget']['average'] %></p>
    <p><%= @shop['budget_memo'] %></p>
  </div>

  <div class="link_area">
    <a href="<%= @shop['urls']['pc'] %>" target="_blank" rel="noopener noreferrer">予約する（外部サイト）</a> <br>
    <%= link_to "地図を開く", "https://www.google.com/maps/search/?api=1&query=#{URI.encode_www_form_component(@shop['address'])}", target: "_blank" %> <br>
    <%= link_to "店舗URL", @shop['urls']['pc'], target: "_blank" %>  <br>
    <% if @shop['coupon_urls'] %>
      <a href="<%= @shop['coupon_urls']['pc'] %>" target="_blank" rel="noopener noreferrer">クーポンURL（外部サイト）</a> <br>
    <% end %>
  </div>
</div>
<div class="footer_area">
  <footer>
    <p>Powered by <a href="http://webservice.recruit.co.jp/">ホットペッパーグルメ Webサービス</a></p>
  </footer>
</div>