config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'home#index'
  post '/mypage/new', to: 'mypage#new', as: 'new_mypage'
  post '/mypage/destroy', to: 'mypage#destroy', as: 'destroy_mypage'
  post '/mypage/create', to: 'mypage#create', as: 'create_mypage'
  post '/mypage/increase_points', to: 'mypage#increase_points', as: 'increase_points_mypage' # テスト用
  post 'search/create', to: 'search#create', as: 'create_search'
  get 'search/update', to: 'search#update', as: 'update_search'
  resources :search, only: [:index, :new, :show]
  resource :mypage, controller: 'mypage', only: [:show, :new, :destroy, :create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="header">
    <header>
      <h1>Finding Yummy</h1>
      <div class="header_menue">
        <% if user_signed_in? %>
          <%= link_to 'マイページ', mypage_path, class: 'header_mypage', target: "_blank" %>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'ログイン', new_user_session_path, class: 'header_mypage' %>
        <% end %>
      </div>
    </header>
  </div>
<h1>検索方法選択画面</h1>

<%= button_to "検索を開始", search_index_path, method: :get %>

<div class="footer_area">
    <footer>
        <p>Powered by <a href="http://webservice.recruit.co.jp/">ホットペッパーグルメ Webサービス</a></p>
    </footer>
</div>