config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'home#index'
  post '/mypage/new', to: 'mypage#new', as: 'new_mypage'
  post '/mypage/destroy', to: 'mypage#destroy', as: 'destroy_mypage'
  post '/mypage/create', to: 'mypage#create', as: 'create_mypage'
  post '/mypage/increase_points', to: 'mypage#increase_points', as: 'increase_points_mypage' # テスト用
  post 'search/create', to: 'search#create', as: 'create_search'
  get 'search/update', to: 'search#update', as: 'update_search'
  resources :search, only: [:index, :new, :show]
  resource :mypage, controller: 'mypage', only: [:show, :new, :destroy, :create]
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  # マイページの表示
  def show
    @user = current_user
    @book = Bookmark.where(user_id: @user.id)
    puts @book.inspect
  end

  # ブックマークの登録
  def new
    @bookmark = Bookmark.new(user_id: current_user.id, shop_id: params[:shop_id], shop_name: params[:shop_name])
    if @bookmark.save
      flash[:notice] = "ブックマークが正常に登録されました。"
    else
      flash[:alert] = "ブックマークの登録に失敗しました。"
    end
    redirect_back(fallback_location: root_path)
  end

  # ブックマークの削除

  def destroy
    @bookmark = Bookmark.find(params[:bookmark])
    @bookmark.destroy
    flash[:notice] = "ブックマークが正常に削除されました。"
    redirect_to mypage_path
  end

  # レビューの作成
  def create
    @review = Review.find_or_create_by(shop_id: params[:shop_id], user_id: current_user.id)
    @review.good = (@review.good || 0) + params[:good].to_i
    @review.bad = (@review.bad || 0) + params[:bad].to_i

    # ユーザーの所持ポイントからレビューに付けるポイントを引く（今回はテストアカウントが無いため、ゼロ以下でも無視して付与できる）
    current_user.points -= params[:good].to_i + params[:bad].to_i

    if @review.save && current_user.save
      redirect_back(fallback_location: mypage_path, notice: 'ポイントを付けました')
    else
      render :new
    end
  end

  # テスト用、ポイントを一万点増やす
  def increase_points
    current_user.points += 10000
    current_user.save
    redirect_to mypage_path, notice: 'ポイントが一万点増えました！'
  end


  private

  def review_params
    params.require(:review).permit(:good, :bad)
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/show.html.erb
<div class="header">
  <header>
    <h1>Finding Yummy</h1>
  </header>
</div>

<h1>マイページ</h1>
<%= link_to '編集', edit_user_registration_path %> <br>
<strong>ユーザー名:</strong>
<p><%= @user.username %></p>

<strong>メール:</strong>
<p><%= @user.email %></p>

<strong>ポイント:</strong>
<p><%= @user.points %>P</p>
<%= button_to 'ポイント獲得', increase_points_mypage_path %> <br>


<strong>ブックマークリスト:</strong>
<% @book.each do |bookmark| %>
  <div class="booklist">
    <p><%= bookmark.shop_name %></p>
    <p>登録日時: <%= bookmark.created_at %></p>
    <%= form_with url: destroy_mypage_path, method: :post do |form| %>
        <%= form.hidden_field :bookmark, value: bookmark.id %>
        <%= form.submit "消去" %>
    <% end %>
  </div>
<% end %>

<div class="footer_area">
  <footer>
      <p>Powered by <a href="http://webservice.recruit.co.jp/">ホットペッパーグルメ Webサービス</a></p>
  </footer>
</div>